FROM python:3.10

# Ref: https://github.com/j3soon/docker-vulkan-runtime
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
RUN apt-get update && apt-get install -y \
    libgl1 libglu1-mesa vulkan-tools libxrandr2 \
    && rm -rf /var/lib/apt/lists/*
RUN cat > /etc/vulkan/icd.d/nvidia_icd.json <<EOF
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.194"
    }
}
EOF

# Ref: https://docs.isaacsim.omniverse.nvidia.com/latest/installation/install_python.html
RUN pip install isaacsim[all]==4.5.0 --extra-index-url https://pypi.nvidia.com \
    && pip install isaacsim[extscache]==4.5.0 --extra-index-url https://pypi.nvidia.com

# Following Isaac Sim's warning message
ENV OMNI_KIT_ACCEPT_EULA=YES
ENV OMNI_KIT_ALLOW_ROOT=1
ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.ros2_bridge/humble/lib

# Reset entrypoint and command
ENTRYPOINT []
CMD ["/bin/bash"]
