FROM python:3.10

# Ref: https://github.com/j3soon/docker-vulkan-runtime
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
RUN apt-get update && apt-get install -y \
    libgl1 vulkan-tools \
    && rm -rf /var/lib/apt/lists/*
RUN cat > /etc/vulkan/icd.d/nvidia_icd.json <<EOF
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.194"
    }
}
EOF
RUN mkdir -p /usr/share/glvnd/egl_vendor.d && \
    cat > /usr/share/glvnd/egl_vendor.d/10_nvidia.json <<EOF
{
    "file_format_version" : "1.0.0",
    "ICD" : {
        "library_path" : "libEGL_nvidia.so.0"
    }
}
EOF
RUN cat > /etc/vulkan/implicit_layer.d/nvidia_layers.json <<EOF
{
    "file_format_version" : "1.0.0",
    "layer": {
        "name": "VK_LAYER_NV_optimus",
        "type": "INSTANCE",
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.194",
        "implementation_version" : "1",
        "description" : "NVIDIA Optimus layer",
        "functions": {
            "vkGetInstanceProcAddr": "vk_optimusGetInstanceProcAddr",
            "vkGetDeviceProcAddr": "vk_optimusGetDeviceProcAddr"
        },
        "enable_environment": {
            "__NV_PRIME_RENDER_OFFLOAD": "1"
        },
        "disable_environment": {
            "DISABLE_LAYER_NV_OPTIMUS_1": ""
        }
    }
}
EOF

# Install `libglu1-mesa` for Iray and `libxrandr2` to support Isaac Sim WebRTC streaming
RUN apt-get update && apt-get install -y \
    libglu1-mesa libxrandr2 \
    && rm -rf /var/lib/apt/lists/*
# Ref: https://docs.isaacsim.omniverse.nvidia.com/latest/installation/install_python.html
RUN pip install isaacsim==4.0.0.0 --extra-index-url https://pypi.nvidia.com \
    && pip install isaacsim-extscache-physics==4.0.0.0 isaacsim-extscache-kit==4.0.0.0 isaacsim-extscache-kit-sdk==4.0.0.0 --extra-index-url https://pypi.nvidia.com

# Following Isaac Sim's warning message
ENV OMNI_KIT_ACCEPT_EULA=YES
ENV OMNI_KIT_ALLOW_ROOT=1
ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.ros2_bridge/humble/lib

# Reset entrypoint and command
ENTRYPOINT []
CMD ["/bin/bash"]
